# Base image
FROM gradle:6.9.0-jdk11
# Set working directory so that all subsequent command runs in this folder
WORKDIR /prior-auth-client
# Copy app files to container
COPY --chown=gradle:gradle . .
RUN gradle installBootDist
# Expose port to access the app
EXPOSE 9090
EXPOSE 9091
# Command to run our app
CMD ./dockerRunnerDev.sh